version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - k3rn31p4nic
  labels:
  - dependency
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: eslint
    versions:
    - 7.20.0
